### ISSUE TITLE
Cannot build documentation in Nix

### ISSUE THREAD

**Issue by milogert** [esensar/nvim-dev-container#74]
**Version**
 - `f798d39b10f29a4ee2bf36e5a513832171333d1a`
 - Mac OS 12.4 with Nix and home-mananger

**Describe the bug**
When adding the plugin via the `buildVimPlugin` function in Nix I get a build error like

```
error: builder for '/nix/store/f9w6ckd4wfcqbf0v0iwzjwm2ghg9m58q-vimplugin-nvim-dev-container.drv' failed with exit code 1;
       last 10 log lines:
       > source root is source
       > patching sources
       > configuring
       > no configure script, doing nothing
       > installing
       > post-installation fixup
       > Executing vimPluginGenTags
       > Building help tags
       > Error detected while processing command line:
       > E154: Duplicate tag "devcontainer" in file /nix/store/y947na8drfggdpkr5w55hq5x4p88cs74-vimplugin-nvim-dev-container/./doc/devcontainer.txtFailed to build help tags!
```

As far as I can tell there is a duplicate help tag in these two spots:
- https://github.com/esensar/nvim-dev-container/blob/f798d39b10f29a4ee2bf36e5a513832171333d1a/doc/devcontainer.txt#L3
- https://github.com/esensar/nvim-dev-container/blob/f798d39b10f29a4ee2bf36e5a513832171333d1a/doc/devcontainer.txt#L896

Because of the function in Nix it's required that the documentation is built successfully to install the plugin.

**Expected behavior**
The docs should build and there should not be a duplicate help tag.

**Provide logs if possible**
No logs for the plugin itself.

**Comment by esensar** [comment]
Thank you for reporting this issue. I have just updated the docs, so it should be working fine now.

**Comment by milogert** [comment]
Wow, what an incredibly fast fix. I am able to install this now. Thanks!
