### ISSUE TITLE
Use Engine API to manage containers

### ISSUE THREAD

**Issue by mkykadir** [esensar/nvim-dev-container#77]
Docker [provides](https://docs.docker.com/engine/api/) standardized Engine API through UNIX socket (and TCP socket for Windows). This way would be more standardized and well documented than current command output parsing. 

Also another advantage would be the [Podman](https://podman.io/) support. Podman is rootless alternative for Docker which has fully compatible commands. But command outputs are different from Docker, thus currently extension cannot be used with it. But Podman supports Engine API.

**Comment by esensar** [comment]
Moved to https://codeberg.org/esensar/nvim-dev-container/issues/77
